# Generated by Django 3.2 on 2021-11-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(unique=True)),
                ('name', models.TextField()),
                ('degree', models.TextField()),
                ('workyear', models.TextField()),
                ('workarea', models.TextField()),
                ('job_name', models.TextField()),
            ],
        ),
    ]
