# Generated by Django 3.2 on 2021-11-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='degree',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='workarea',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='workyear',
            field=models.TextField(null=True),
        ),
    ]
