# Generated by Django 3.2 on 2021-11-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.CharField(max_length=50, unique=True, verbose_name='职位id')),
                ('job_name', models.CharField(max_length=200, verbose_name='职位名称')),
                ('job_href', models.TextField(verbose_name='职位原链接')),
                ('coid', models.CharField(max_length=50, unique=True, verbose_name='公司id')),
                ('company_name', models.CharField(max_length=200, verbose_name='公司名称')),
                ('company_href', models.TextField(verbose_name='公司原链接')),
                ('providesalary_text', models.TextField(verbose_name='薪资水平')),
                ('workarea', models.CharField(max_length=200, verbose_name='地区编码')),
                ('workarea_text', models.CharField(max_length=200, verbose_name='工作地区')),
                ('companytype_text', models.CharField(max_length=200, verbose_name='公司类型')),
                ('degreefrom', models.CharField(max_length=200, verbose_name='学历编码')),
                ('degreefrom_text', models.CharField(max_length=200, verbose_name='学历')),
                ('workyear', models.CharField(max_length=200, verbose_name='工作经验编码')),
                ('workyear_text', models.CharField(max_length=200, verbose_name='工作经验编码')),
                ('jobwelf', models.TextField(verbose_name='工作福利')),
                ('companysize_text', models.TextField(max_length=200, verbose_name='公司规模')),
                ('companyind_text', models.TextField(max_length=200, verbose_name='公司行业')),
                ('providesalary_min', models.FloatField(null=True, verbose_name='薪资最小值(千/月)')),
                ('providesalary_max', models.FloatField(null=True, verbose_name='薪资最大值(千/月)')),
                ('attribute', models.TextField(verbose_name='职位属性')),
                ('jobinfo', models.TextField(verbose_name='职位详情')),
            ],
            options={
                'verbose_name': '职位',
                'verbose_name_plural': '职位',
                'db_table': 'job',
            },
        ),
    ]
