# Generated by Django 3.2 on 2021-11-08 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='coid',
            field=models.CharField(max_length=50, verbose_name='公司id'),
        ),
    ]
