# Generated by Django 3.2 on 2021-11-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_coid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_href',
            field=models.TextField(editable=False, verbose_name='公司原链接'),
        ),
        migrations.AlterField(
            model_name='job',
            name='degreefrom',
            field=models.CharField(editable=False, max_length=200, verbose_name='学历编码'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_href',
            field=models.TextField(editable=False, verbose_name='职位原链接'),
        ),
        migrations.AlterField(
            model_name='job',
            name='workarea',
            field=models.CharField(editable=False, max_length=200, verbose_name='地区编码'),
        ),
        migrations.AlterField(
            model_name='job',
            name='workyear',
            field=models.CharField(editable=False, max_length=200, verbose_name='工作经验编码'),
        ),
        migrations.AlterField(
            model_name='job',
            name='workyear_text',
            field=models.CharField(max_length=200, verbose_name='工作经验'),
        ),
    ]
